### ISSUE TITLE
Cannot upload my .hex files

### ISSUE THREAD

**Issue by nitinsane** [maximevince/arduino-as-pic18f-programmer#2]
I just downloaded and trying to make it work with PIC18F4550 chip. I can flash the blink.hex program in this repository and get my LED to flash. However, when I try to upload my own program, it seems erase, program and verify completes but I get this error

Success
Verify ID memory...

Traceback (most recent call last):
  File "C:\Users\nitin\Documents\Github\arduino-as-pic18f-programmer\python\pic_programmer.py", line 388, in <module>
    main()
  File "C:\Users\nitin\Documents\Github\arduino-as-pic18f-programmer\python\pic_programmer.py", line 277, in main
    buf += r
TypeError: can only concatenate str (not "bytes") to str

**Comment by maximevince** [comment]
Hi,

I haven't tested this in a while...
It seems like we're mixing bytes and strings here. (Which was okay in Python 2, from which I ported this code)

I have just pushed a little change to a separate branch, that might fix this particular error:
https://github.com/maximevince/arduino-as-pic18f-programmer/tree/bytes-vs-str-fix
Can you try again?
If it keeps failing, please provide the .HEX file you used, if possible.

Thanks

**Comment by maximevince** [comment]
Fix was merged: https://github.com/maximevince/arduino-as-pic18f-programmer/commit/1e5685ef0cd475206a6e063ea8dc89d8dcd37ebd
