### ISSUE TITLE
Support for PIC18F(06|16)Q41

### ISSUE THREAD

**Issue by Flole998** [maximevince/arduino-as-pic18f-programmer#4]
Hi,

thank you very much for the work you did. Have you looked into some newer PICs like the 18F06 or 16F16? Should the code work with those aswell?

Thanks again

**Comment by maximevince** [comment]
Hi, I haven't looked at those.
These days I'm mostly working on ARM, ESP and RISC-V targets.
If the PICs you mention are using the same debugger/programmer protocol, it might suffice to just add the corresponding IDs to the code, so they get recognized.

Let me know if you try!

-------- Original Message --------

**Comment by Flole998** [comment]
They use a completely different protocol. I implemented my own solution to get a firmware into one of those.

**Comment by maximevince** [comment]
Different protocol, not supported by this project.
